import yaml
import base64
import ctypes
import ctypes.wintypes

class DATA_BLOB(ctypes.Structure):
    _fields_ = [
        ('cbData', ctypes.wintypes.DWORD),
        ('pbData', ctypes.POINTER(ctypes.c_char))
    ]

def dpapi_decrypt(encrypted_bytes):
    blob_in = DATA_BLOB()
    blob_in.cbData = len(encrypted_bytes)
    blob_in.pbData = ctypes.create_string_buffer(encrypted_bytes, len(encrypted_bytes))
    blob_out = DATA_BLOB()
    
    if ctypes.windll.crypt32.CryptUnprotectData(
        ctypes.byref(blob_in),
        None,
        None,
        None,
        None,
        0,
        ctypes.byref(blob_out)
    ):
        data = ctypes.string_at(blob_out.pbData, blob_out.cbData)
        ctypes.windll.kernel32.LocalFree(blob_out.pbData)
        return data
    else:
        raise Exception('DPAPI decrypt failed')

# 解析c.pwd
with open(r'C:\Users\xiwei\AppData\Roaming\Huawei\DevEcoStudio26.0\c.pwd', 'r') as f:
    content = f.read()

data = yaml.safe_load(content)
print(f'Type: {type(data)}')
print(f'Keys: {list(data.keys()) if isinstance(data, dict) else "N/A"}')
print(f'encryption: {data.get("encryption")}')
print(f'isAutoGenerated: {data.get("isAutoGenerated")}')
value = data.get('value')
if isinstance(value, bytes):
    print(f'value type: bytes, length: {len(value)}')
    print(f'value first 20 bytes hex: {value[:20].hex()}')
    
    # 尝试用DPAPI解密
    try:
        decrypted = dpapi_decrypt(value)
        print(f'DPAPI decrypted length: {len(decrypted)}')
        print(f'DPAPI decrypted first 20 bytes hex: {decrypted[:20].hex()}')
        
        # 尝试各种解码
        try:
            text = decrypted.decode('utf-8')
            print(f'UTF-8: [{text}]')
        except:
            print('Not UTF-8')
        
        try:
            text = decrypted.decode('utf-16-le')
            print(f'UTF-16LE: [{text}]')
        except:
            print('Not UTF-16LE')
        
        # 尝试跳过前4字节
        try:
            text = decrypted[4:].decode('utf-8')
            print(f'UTF-8 (skip 4): [{text}]')
        except:
            print('Not UTF-8 (skip 4)')
        
        try:
            text = decrypted[4:].decode('utf-16-le')
            print(f'UTF-16LE (skip 4): [{text}]')
        except:
            print('Not UTF-16LE (skip 4)')
        
        # 尝试跳过前4字节，按长度读取
        import struct
        length = struct.unpack('>I', decrypted[:4])[0]
        print(f'Length prefix (BE): {length}')
        try:
            text = decrypted[4:4+length].decode('utf-8')
            print(f'UTF-8 (length-prefixed): [{text}]')
        except:
            pass
        try:
            text = decrypted[4:4+length*2].decode('utf-16-le')
            print(f'UTF-16LE (length-prefixed): [{text}]')
        except:
            pass
        
    except Exception as e:
        print(f'DPAPI decrypt failed: {e}')
elif isinstance(value, str):
    print(f'value type: str, length: {len(value)}')
    print(f'value first 50 chars: {value[:50]}')