package com.xiwei.sujian.ui.compose.workbench.model

sealed class WorkbenchAction {
    data class TogglePanel(val panelId: WorkbenchPanelId) : WorkbenchAction()
    data class ExpandPanel(val panelId: WorkbenchPanelId) : WorkbenchAction()
    data class CollapsePanel(val panelId: WorkbenchPanelId) : WorkbenchAction()
    data class HidePanel(val panelId: WorkbenchPanelId) : WorkbenchAction()
    data class MovePanel(val panelId: WorkbenchPanelId, val zone: DockZone) : WorkbenchAction()
    data class ResizePanel(val panelId: WorkbenchPanelId, val sizeDp: Float, val availableWidthDp: Float = Float.MAX_VALUE) : WorkbenchAction()
    data class ActivateTab(val tabGroupId: String, val panelId: WorkbenchPanelId) : WorkbenchAction()
    data class FloatPanel(val panelId: WorkbenchPanelId) : WorkbenchAction()
    data class DockPanel(val panelId: WorkbenchPanelId, val zone: DockZone) : WorkbenchAction()
    data class MoveFloatingPanel(val panelId: WorkbenchPanelId, val x: Float, val y: Float) : WorkbenchAction()
    data class ApplyPreset(val preset: WorkbenchPreset) : WorkbenchAction()
    data object RestoreLayout : WorkbenchAction()
    data class MovePanelToGroup(val panelId: WorkbenchPanelId, val tabGroupId: String) : WorkbenchAction()
    data class CreateDockGroup(val groupId: String, val zone: DockZone, val order: Int) : WorkbenchAction()
    data class ReorderPanel(val panelId: WorkbenchPanelId, val newOrder: Int) : WorkbenchAction()
    data class ReorderDockGroup(val groupId: String, val newOrder: Int) : WorkbenchAction()
    data class BringFloatingToFront(val panelId: WorkbenchPanelId) : WorkbenchAction()
    data class ResizeFloatingPanel(val panelId: WorkbenchPanelId, val widthDp: Float, val heightDp: Float) : WorkbenchAction()
    data class FloatPanelAt(val panelId: WorkbenchPanelId, val x: Float, val y: Float) : WorkbenchAction()
    data class ActivateOverlayPanel(val panelId: WorkbenchPanelId) : WorkbenchAction()
    data class ResizePanelDelta(val panelId: WorkbenchPanelId, val deltaDp: Float, val availableWidthDp: Float = Float.MAX_VALUE) : WorkbenchAction()
    data class ResizeDockGroup(val groupId: String, val zone: DockZone, val sizeDp: Float) : WorkbenchAction()
    data class ClampFloatingPanels(val maxWidthDp: Float, val maxHeightDp: Float) : WorkbenchAction()
}
