//! # 设置页 editor section（#628 拆分）

use super::{PlatformVisibility, SettingItemDef, SettingSectionDef};

/// 构建 editor section（order: 20）。
pub(super) fn build_editor_section() -> SettingSectionDef {
    SettingSectionDef {
        id: "editor".into(),
        title_key: "settings.section.editor".into(),
        order: 20,
        platform_visibility: PlatformVisibility::All,
        items: vec![
            SettingItemDef {
                id: "auto_indent_enabled".into(),
                title_key: "settings.item.auto_indent_enabled".into(),
                description_key: None,
                kind: super::SettingControlKind::Switch,
                value_key: "auto_indent_enabled".into(),
                order: 1,
                platform_visibility: PlatformVisibility::All,
                min_value: None,
                max_value: None,
                step_value: None,
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
            SettingItemDef {
                id: "auto_indent_width".into(),
                title_key: "settings.item.auto_indent_width".into(),
                description_key: None,
                kind: super::SettingControlKind::Slider,
                value_key: "auto_indent_width".into(),
                order: 2,
                platform_visibility: PlatformVisibility::All,
                min_value: Some(0.0),
                max_value: Some(8.0),
                step_value: Some(0.5),
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
            SettingItemDef {
                id: "typing_animation_enabled".into(),
                title_key: "settings.item.typing_animation_enabled".into(),
                description_key: None,
                kind: super::SettingControlKind::Switch,
                value_key: "typing_animation_enabled".into(),
                order: 3,
                platform_visibility: PlatformVisibility::All,
                min_value: None,
                max_value: None,
                step_value: None,
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
            SettingItemDef {
                id: "typing_animation_duration_ms".into(),
                title_key: "settings.item.typing_animation_duration_ms".into(),
                description_key: None,
                kind: super::SettingControlKind::Slider,
                value_key: "typing_animation_duration_ms".into(),
                order: 4,
                platform_visibility: PlatformVisibility::All,
                min_value: Some(30.0),
                max_value: Some(1000.0),
                step_value: Some(10.0),
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
            SettingItemDef {
                id: "smooth_cursor_enabled".into(),
                title_key: "settings.item.smooth_cursor_enabled".into(),
                description_key: None,
                kind: super::SettingControlKind::Switch,
                value_key: "smooth_cursor_enabled".into(),
                order: 5,
                platform_visibility: PlatformVisibility::All,
                min_value: None,
                max_value: None,
                step_value: None,
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
            SettingItemDef {
                id: "smooth_cursor_duration_ms".into(),
                title_key: "settings.item.smooth_cursor_duration_ms".into(),
                description_key: None,
                kind: super::SettingControlKind::Slider,
                value_key: "smooth_cursor_duration_ms".into(),
                order: 6,
                platform_visibility: PlatformVisibility::All,
                min_value: Some(30.0),
                max_value: Some(1000.0),
                step_value: Some(10.0),
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
        ],
    }
}
