//! # 设置页 sync section（#628 拆分）

use super::{PlatformVisibility, SettingItemDef, SettingSectionDef};

/// 构建 sync section（order: 40）。
// sync section 含 9 个设置项，是数据定义性质的函数，行数多但无分支复杂度。
#[allow(clippy::too_many_lines)]
pub(super) fn build_sync_section() -> SettingSectionDef {
    SettingSectionDef {
        id: "sync".into(),
        title_key: "settings.section.sync".into(),
        order: 40,
        platform_visibility: PlatformVisibility::All,
        items: vec![
            SettingItemDef {
                id: "sync_enabled".into(),
                title_key: "settings.item.sync_enabled".into(),
                description_key: None,
                kind: super::SettingControlKind::Switch,
                value_key: "sync_enabled".into(),
                order: 1,
                platform_visibility: PlatformVisibility::All,
                min_value: None,
                max_value: None,
                step_value: None,
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
            SettingItemDef {
                id: "github_repo".into(),
                title_key: "settings.item.github_repo".into(),
                description_key: None,
                kind: super::SettingControlKind::TextPlain,
                value_key: "github_repo".into(),
                order: 2,
                platform_visibility: PlatformVisibility::All,
                min_value: None,
                max_value: None,
                step_value: None,
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
            SettingItemDef {
                id: "branch".into(),
                title_key: "settings.item.branch".into(),
                description_key: None,
                kind: super::SettingControlKind::TextPlain,
                value_key: "branch".into(),
                order: 3,
                platform_visibility: PlatformVisibility::All,
                min_value: None,
                max_value: None,
                step_value: None,
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
            SettingItemDef {
                id: "token".into(),
                title_key: "settings.item.token".into(),
                description_key: None,
                kind: super::SettingControlKind::TextSecret,
                value_key: "token".into(),
                order: 4,
                platform_visibility: PlatformVisibility::All,
                min_value: None,
                max_value: None,
                step_value: None,
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
            SettingItemDef {
                id: "auto_sync".into(),
                title_key: "settings.item.auto_sync".into(),
                description_key: None,
                kind: super::SettingControlKind::Switch,
                value_key: "auto_sync".into(),
                order: 5,
                platform_visibility: PlatformVisibility::All,
                min_value: None,
                max_value: None,
                step_value: None,
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
            SettingItemDef {
                id: "sync_interval_seconds".into(),
                title_key: "settings.item.sync_interval_seconds".into(),
                description_key: None,
                kind: super::SettingControlKind::Slider,
                value_key: "sync_interval_seconds".into(),
                order: 6,
                platform_visibility: PlatformVisibility::All,
                min_value: Some(60.0),
                max_value: Some(3600.0),
                step_value: Some(60.0),
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
            SettingItemDef {
                id: "sync_dry_run".into(),
                title_key: "settings.item.sync_dry_run".into(),
                description_key: None,
                kind: super::SettingControlKind::Action,
                value_key: "sync_dry_run".into(),
                order: 7,
                platform_visibility: PlatformVisibility::All,
                min_value: None,
                max_value: None,
                step_value: None,
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
            SettingItemDef {
                id: "sync_test_connection".into(),
                title_key: "settings.item.sync_test_connection".into(),
                description_key: None,
                kind: super::SettingControlKind::Action,
                value_key: "sync_test_connection".into(),
                order: 8,
                platform_visibility: PlatformVisibility::All,
                min_value: None,
                max_value: None,
                step_value: None,
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
            SettingItemDef {
                id: "sync_now".into(),
                title_key: "settings.item.sync_now".into(),
                description_key: None,
                kind: super::SettingControlKind::Action,
                value_key: "sync_now".into(),
                order: 9,
                platform_visibility: PlatformVisibility::All,
                min_value: None,
                max_value: None,
                step_value: None,
                select_options: None,
                requires_restart: false,
                is_experimental: false,
            },
        ],
    }
}
