<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<!-- Generated by lupdate or manual placeholder -->
<context>
    <name>main</name>
    <message>
        <source>作品</source>
        <translation>作品</translation>
    </message>
</context>
</TS>
