// =============================================================================
// mod.rs — Linux_qt 客户端 QObject 后端聚合与生命周期管理器
// =============================================================================

pub mod app_backend;
pub mod linux_qt_layout_plan_dto;
pub mod linux_theme_controller;
pub mod diagnostics;
pub mod json_utils;
pub(crate) mod message_key_mapper;

use qmetaobject::prelude::*;

pub use app_backend::{
    AppBackend, EditorBackend, ProjectBackend, SettingsBackend, StarMapBackend, SyncBackend,
    WorkspaceBackend,
};
pub use linux_theme_controller::LinuxThemeController;

/// Immutable domain state snapshot generated by AppBackend after each mutation.
///
/// QObject getters read only from this snapshot — they never borrow AppBackend.
/// This eliminates the borrow-conflict fallback problem where cached defaults
/// masked read failures.
///
/// The snapshot is updated inside `AppRef::with_app_mut` after the mutation
/// completes successfully, so it is always consistent with the latest
/// AppBackend state visible to QML.
#[derive(Clone, Debug)]
pub(crate) struct DomainSnapshot {
    pub save_status: String,
    pub word_count: i32,
    pub error_message: String,
    pub selected_item_id: String,
    pub has_selected_chapter_prop: bool,
    pub chapter_path: String,
    pub setting_font_size: f32,
    pub setting_line_spacing: f32,
    pub setting_auto_save_enabled: bool,
    pub setting_auto_save_delay_ms: u32,
    pub setting_auto_indent_enabled: bool,
    pub setting_auto_indent_width: f32,
    pub setting_smooth_cursor_enabled: bool,
    pub setting_typing_animation_enabled: bool,
    pub setting_smooth_cursor_duration_ms: u32,
    pub setting_typing_animation_duration_ms: u32,
    pub setting_coordinated_text_cursor_animation_enabled: bool,
    pub has_workspace: bool,
    pub sync_enabled: bool,
    pub sync_auto_sync: bool,
    pub sync_interval: u32,
    pub has_sync_token: bool,
    pub sync_in_progress: bool,
    pub sync_can_run: bool,
    pub ai_available: bool,
    pub ai_enabled: bool,
    pub setting_linux_qt_sidebar_width: f64,
    pub setting_linux_qt_editor_width: f64,
    pub setting_diagnostics_enabled: bool,
    pub setting_diagnostics_verbose: bool,
    pub setting_dynamic_color_enabled: bool,
    pub system_is_dark: bool,
    pub appearance_mode: String,
    pub selected_palette_id: String,
    pub has_selected_chapter: bool,
    pub selected_chapter_exists: bool,
}

impl Default for DomainSnapshot {
    fn default() -> Self {
        Self {
            save_status: String::new(),
            word_count: 0,
            error_message: String::new(),
            selected_item_id: String::new(),
            has_selected_chapter_prop: false,
            chapter_path: String::new(),
            setting_font_size: 16.0,
            setting_line_spacing: 1.5,
            setting_auto_save_enabled: true,
            setting_auto_save_delay_ms: 1500,
            setting_auto_indent_enabled: true,
            setting_auto_indent_width: 2.0,
            setting_smooth_cursor_enabled: true,
            setting_typing_animation_enabled: true,
            setting_smooth_cursor_duration_ms: 80,
            setting_typing_animation_duration_ms: 100,
            setting_coordinated_text_cursor_animation_enabled: true,
            has_workspace: false,
            sync_enabled: false,
            sync_auto_sync: false,
            sync_interval: 300,
            has_sync_token: false,
            sync_in_progress: false,
            sync_can_run: false,
            ai_available: false,
            ai_enabled: false,
            setting_linux_qt_sidebar_width: 240.0,
            setting_linux_qt_editor_width: 0.0,
            setting_diagnostics_enabled: true,
            setting_diagnostics_verbose: true,
            setting_dynamic_color_enabled: false,
            system_is_dark: false,
            appearance_mode: "system".to_string(),
            selected_palette_id: String::new(),
            has_selected_chapter: false,
            selected_chapter_exists: false,
        }
    }
}

/// Shared reference to AppBackend via Rc<RefCell<>>.
///
/// Domain backends call `with_app` / `with_app_mut` which go through
/// `RefCell::try_borrow` / `RefCell::try_borrow_mut`, returning
/// `Result<R, AppBorrowError>` on borrow conflict instead of silently
/// returning a default value.
///
/// After each successful `with_app_mut`, the shared `DomainSnapshot` is
/// updated from the current AppBackend state. QObject getters read only
/// from the snapshot — they never re-borrow AppBackend, so there is no
/// borrow conflict on reads and no silent default masking.
///
/// # Ownership and lifetime
///
/// `Rc<RefCell<AppBackend>>` is the single ownership root. All domain backends
/// hold a clone of the same `Rc`, so `AppBackend` lives until the last reference
/// is dropped. `Rc` is `!Send + !Sync`, so all access is confined to the GUI
/// thread — the Rust type system enforces this automatically.
///
/// # Destruction order
///
/// `app` MUST be the last field in `BackendRuntime` so that all domain backends
/// (which hold AppRef clones pointing into app) are dropped first.
/// See <https://doc.rust-lang.org/reference/destructors.html>.
#[derive(Clone)]
pub struct AppRef {
    inner: std::rc::Rc<std::cell::RefCell<AppBackend>>,
    snapshot: std::rc::Rc<std::cell::RefCell<DomainSnapshot>>,
}

#[derive(Debug, Clone)]
pub struct AppBorrowError;

impl std::fmt::Display for AppBorrowError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "AppBackend borrow conflict: another borrow is active")
    }
}

impl std::error::Error for AppBorrowError {}

impl AppRef {
    pub fn new(app: std::rc::Rc<std::cell::RefCell<AppBackend>>) -> Self {
        let snapshot = std::rc::Rc::new(std::cell::RefCell::new(DomainSnapshot::default()));
        Self { inner: app, snapshot }
    }

    pub fn rc(&self) -> &std::rc::Rc<std::cell::RefCell<AppBackend>> {
        &self.inner
    }

    pub fn snapshot(&self) -> &std::rc::Rc<std::cell::RefCell<DomainSnapshot>> {
        &self.snapshot
    }

    pub fn with_app<R>(&self, f: impl FnOnce(&AppBackend) -> R) -> Result<R, AppBorrowError> {
        match self.inner.try_borrow() {
            Ok(guard) => Ok(f(&guard)),
            Err(_) => {
                crate::backend::app_backend::debug_error_static(
                    "app_ref",
                    "BORROW_CONFLICT",
                    "AppBackend already borrowed mutately; operation skipped",
                );
                Err(AppBorrowError)
            }
        }
    }

    pub fn with_app_mut<R>(&self, f: impl FnOnce(&mut AppBackend) -> R) -> Result<R, AppBorrowError> {
        match self.inner.try_borrow_mut() {
            Ok(mut guard) => {
                let result = f(&mut guard);
                guard.update_snapshot(&self.snapshot);
                Ok(result)
            }
            Err(_) => {
                crate::backend::app_backend::debug_error_static(
                    "app_ref",
                    "BORROW_CONFLICT",
                    "AppBackend already borrowed; operation skipped",
                );
                Err(AppBorrowError)
            }
        }
    }

    pub(crate) fn init_snapshot(&self) {
        if let Ok(guard) = self.inner.try_borrow() {
            guard.update_snapshot(&self.snapshot);
        }
    }
}

impl Default for AppRef {
    fn default() -> Self {
        Self {
            inner: std::rc::Rc::new(std::cell::RefCell::new(AppBackend::default())),
            snapshot: std::rc::Rc::new(std::cell::RefCell::new(DomainSnapshot::default())),
        }
    }
}

/// Owns every QObject registered into the QML root context.
///
/// Qt only receives raw QObject pointers from `set_object_property`; this
/// runtime keeps the Rust QObjectBox owners alive until after `engine.exec()`.
///
/// **Field order matters**: Rust destroys fields in declaration order.
/// `app` MUST be the last field so that all domain backends
/// (which hold AppRef clones pointing into app) are dropped first.
/// See <https://doc.rust-lang.org/reference/destructors.html>.
pub struct BackendRuntime {
    workspace_backend: QObjectBox<WorkspaceBackend>,
    project_backend: QObjectBox<ProjectBackend>,
    editor_backend: QObjectBox<EditorBackend>,
    settings_backend: QObjectBox<SettingsBackend>,
    sync_backend: QObjectBox<SyncBackend>,
    starmap_backend: QObjectBox<StarMapBackend>,
    theme_controller: QObjectBox<LinuxThemeController>,
    app: std::rc::Rc<std::cell::RefCell<AppBackend>>,
}

impl BackendRuntime {
    pub fn new() -> Self {
        let app = std::rc::Rc::new(std::cell::RefCell::new(AppBackend::default()));
        {
            let mut r = app.borrow_mut();
            r.current_setting_diagnostics_enabled = true;
            r.current_setting_diagnostics_verbose = true;
        }
        let app_ref = AppRef::new(app.clone());
        app_ref.init_snapshot();

        Self {
            workspace_backend: QObjectBox::new(WorkspaceBackend::new(app_ref.clone())),
            project_backend: QObjectBox::new(ProjectBackend::new(app_ref.clone())),
            editor_backend: QObjectBox::new(EditorBackend::new(app_ref.clone())),
            settings_backend: QObjectBox::new(SettingsBackend::new(app_ref.clone())),
            sync_backend: QObjectBox::new(SyncBackend::new(app_ref.clone())),
            starmap_backend: QObjectBox::new(StarMapBackend::new(app_ref.clone())),
            theme_controller: QObjectBox::new(LinuxThemeController::new(app_ref)),
            app,
        }
    }

    pub fn register_context_properties(&self, engine: &mut QmlEngine) {
        // SAFETY: Rc<RefCell<AppBackend>> heap-allocates and pins the RefCell;
        // Rc is !Send + !Sync, confining access to the GUI thread.
        // QObjectPinned::new borrows the RefCell only for set_object_property.
        let pinned: qmetaobject::QObjectPinned<AppBackend> =
            unsafe { qmetaobject::QObjectPinned::new(&self.app) };
        engine.set_object_property("backend".into(), pinned);
        engine.set_object_property("appBackend".into(), pinned);
        engine.set_object_property("workspaceBackend".into(), self.workspace_backend.pinned());
        engine.set_object_property("projectBackend".into(), self.project_backend.pinned());
        engine.set_object_property("editorBackend".into(), self.editor_backend.pinned());
        engine.set_object_property("settingsBackend".into(), self.settings_backend.pinned());
        engine.set_object_property("syncBackend".into(), self.sync_backend.pinned());
        engine.set_object_property("starmapBackend".into(), self.starmap_backend.pinned());
        engine.set_object_property("themeController".into(), self.theme_controller.pinned());
    }
}
