#!/usr/bin/env node
// =============================================================================
// hvigor-wrapper.js - Hvigor wrapper for CI environments
// =============================================================================
// This file is normally generated by ohpm install from @ohos/hvigor-ohos.
// In CI where ohpm cannot access Huawei's commercial registry,
// we provide this wrapper that delegates to @ohos/hvigor's CLI directly.
// =============================================================================

const path = require('path');
const fs = require('fs');

// Resolve @ohos/hvigor from oh_modules or node_modules
function findHvigorBin() {
  const searchDirs = [
    path.resolve(__dirname, '..', 'oh_modules', '@ohos', 'hvigor'),
    path.resolve(__dirname, '..', 'node_modules', '@ohos', 'hvigor'),
  ];

  for (const dir of searchDirs) {
    const binPath = path.join(dir, 'bin', 'hvigor.js');
    if (fs.existsSync(binPath)) {
      return binPath;
    }
  }
  return null;
}

const hvigorBin = findHvigorBin();
if (!hvigorBin) {
  console.error('ERROR: @ohos/hvigor not found in oh_modules or node_modules.');
  console.error('Please ensure @ohos/hvigor is installed.');
  process.exit(1);
}

// Load and execute hvigor CLI
require(hvigorBin);