name: Android Native Debug Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x apps/android_native/gradlew

      - name: Build Android Native Debug APK
        run: |
          cd apps/android_native
          ./gradlew assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-native-debug-apk
          path: apps/android_native/app/build/outputs/apk/debug/app-debug.apk
